[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
dotenv = "0.15.0"
serde_json = "1.0.140"
tera = "1"
mysql = "24.0"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio-rustls", "chrono"] }
serde = { version = "1", features = ["derive"] }
dotenvy = "0.15"
reqwest = { version = "0.11", features = ["json", "stream"] }

actix-files = "0.6"
chrono = { version = "0.4", features = ["serde"] }
webbrowser = "0.8"
actix-multipart = "0.4"
futures-util = "0.3"
actix-cors = "0.6"
aws-config = { version = "1.8.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.8.7"
aws-credential-types = "1.2.7"
aws-smithy-types = "1.2.7"
url = "2.5.2"
mime = "0.3"
pdf-extract = "0.6"
sanitize-filename = "0.5"
tempfile = "3.23.0"
rayon = "1.11.0"



[lib]
crate-type = ["cdylib", "rlib"]
name = "backend_lib"  # Tên thư viện (thường là tên project)
path = "src/lib.rs"

